---
title: "Explore Landsat indices"
author: "Hardy Griesbauer"
date: "29/01/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(plotly)

# Load data
load("fdiLS_raw.RData")

```

# summarize spectral indices by site, year and month
```{r}
fdiLS %>% 
  mutate(month=month(date)) %>% # create month column
  mutate(year=year(date)) %>% # create month column
  filter(year<=2005) %>% # limit sites to chronology timeframe
  group_by(site,year,month) %>% 
  summarise(Num=n()) %>% 
  ungroup() %>% 
  group_by(site,month) %>% 
  summarise(Num=n()) %>% # this will give total values for this site/month
  filter(month>=4 & month<=10) %>%  # filter for April to October months
  # pivot_wider(names_from=month,values_from=Num) %>% # move to wider format to examine for missing values
  # dplyr::select(site,year,as.character(4:10)) # need to reorder columns
  
  # plotting to create boxplots
  ggplot()+
  aes(x=month,y=Num)+
  geom_bar(stat="Identity")+
  facet_wrap(~site)+
  ylab("Number of years with at least one scene")

```

Based on this figure, it looks like July, August and September have the most scenes for each site, suggesting we should focus on spectral indices for those three months.



# Explore LS indices to create final dataset
```{r}

x<-
  fdiLS %>% 
  filter(site=="whiteman") 
  
ggplotly(ggplot(data=x)+
  aes(x=date,y=ndvi)+
  geom_line())
  



```